### ISSUE TITLE
timeout setting from $snmp->defaults doesnt work well

### ISSUE THREAD

**Issue by akarelas-pt** [jhthorsen/mojo-snmp#13]
The get method in the following script waits for 6 seconds rather than for 3 seconds:

```perl
#!/opt/perl-5.24.2/bin/perl

use v5.24;
use warnings;
use lib '../local/lib/perl5', '../lib';

use Mojo::SNMP;
use DDP;
use Net::SNMP::Util::OID 'if*';

use experimentals;

my $ip = '127.0.0.1';

my $snmp = Mojo::SNMP->new;
$snmp->defaults({
    community => 'public',
    version => 'v2c',
    timeout => 3,
});

my $base_descr_oid = oid('ifDescr.24');

my $results;
say 'STARTING!!! ', time;
$snmp->get($ip, [$base_descr_oid], sub ($self, $err, $session) {
    if ($err) { say "Error: $err"; }
    $results = $session->var_bind_list;
});
$snmp->wait;
say 'ENDED!!! ', time;

p $results;
```

This script waits for 6 seconds, even though timeout is 3 seconds. In general, it waits for double the seconds stated in the timeout setting.

**Comment by jhthorsen** [comment]
The reason is that https://metacpan.org/pod/Net::SNMP#retries()-set-or-get-the-current-retry-count-for-the-object is set to 1 by default, meaning you have to set `retries => 0` if you want it to timeout after 3 seconds.
